### ISSUE TITLE
Problem with $help command

### ISSUE THREAD

**Issue by whitten** [basilTeam/basil#2]
I ran this on the http://repl.it site 

I tried the $help command at the ? prompt of Basil, and only made it work if I typed a non-intuitive EOF

$ make basil
$ ./basil

┌────────────────────────────────────────┐
│                                        │
│          𝐵𝑎𝑠𝑖𝑙 — version 0.1           │
│                                        │
└────────────────────────────────────────┘

Enter any Basil expression at the prompt, or '$help' for a list of commands!

? $help (I Typed CONTROL-D)
.  (I typed CARRIAGE RETURN)

Commands: 
 - $help                 => prints this command list.
 - $quit                 => exits REPL.
 - $print-tokens <bool>  => toggles token printing.
 - $print-parse <bool>   => toggles parse tree printing.
 - $print-ast <bool>     => toggles AST printing.
 - $print-ssa <bool>     => toggles SSA printing.
 - $print-asm <bool>     => toggles assembly printing.

? ? $quit ( typed CARRIAGE RETURN)
.  (I typed CARRIAGE RETURN)
$ (FINALLY GOT LINUX PROMPT)

Note: I found that I didn't need to type CONTROL-D  I could simply type CARRIAGE RETURN and then another CARRIAGE RETURN at the prompt.
I could also use CONTROL-M or CONTROL-J instead of CARRIAGE RETURN

**Comment by elucent** [comment]
This is intended behavior, and applies to all input to the Basil prompt. As described in `./basil intro`:
![image](https://user-images.githubusercontent.com/9532786/96032304-79d0a980-0e2c-11eb-80f5-b1bb91b0d4cf.png)
It's admittedly unintuitive, but this behavior was chosen after a lot of careful consideration about how to support certain expressions in the REPL. 

Unlike most other languages, indented blocks are permitted almost anywhere in expressions, and there's no special token necessary to open one - it's entirely based on whitespace. This is fine when executing a source file, but it causes some problems in the REPL - when entering a line, how do we know whether it's meant to be evaluated on its own, or if it'll be followed up by an indented block? Without changing the grammar, there's no way to tell. So instead of trying to guess, the REPL will _always_ accept multiple lines of input, only terminating when you give it a blank line.

I think the best solution to this would probably just be to copy the help message from `./basil intro` over to `./basil`. It'll be in our next commit - but that might be a while, there's a lot of uncommitted work since the end of the jam, so we're trying to clean that up privately before our next push.

**Comment by whitten** [comment]
Thank you for taking the time out of your review to answer my question.
Congratulations on winning the Jam.
Do you have a full time job as well as working on basil ?

Dave Whitten
713-870-3834
