### ISSUE TITLE
Dreaming about end-user/programmer use-cases

### ISSUE THREAD

**Issue by dumblob** [basilTeam/basil#27]
I was (again :wink:) dreaming lately about:

1. making [teishi](https://github.com/fpereiro/teishi )-like safety/validation/assert lib work in (mostly) compile-time **instead of** specifying types for each argument of a function separately (yeah, it's pretty radical, but it's vastly more powerful and readable than relying on just argument types in which case one would need to create duplicates of existing functions and existing types just to represent an instance of the tuple `function, types, values` like in Haskell to get about the same expressiveness but at the huge cost of verbosity and "intent obfuscated and scattered all over the app source")
2. having the [SixtyFPS syntax](https://github.com/sixtyfpsui/sixtyfps/tree/master/examples ) ported to native Basil syntax (probably also drawing some inspiration from https://github.com/fpereiro/gotoB and maybe even [ustack](https://github.com/fpereiro/ustack ) and [Jasonelle](https://github.com/jasonelle/jasonelle/ ))
3. having [async stuff as in Julia](https://docs.julialang.org/en/v1/manual/asynchronous-programming/ ) (i.e. syntactically explicit and clear "what it does" and that it's all just "compile-time" macros and thus how it copes with e.g. multithreading etc.) to account for hybrid systems like ["ECS & async"](https://github.com/Pauan/rust-signals/discussions/31#discussioncomment-829947 )
4. seamless "high-level" FFI like [PythonCall](https://cjdoris.github.io/PythonCall.jl/stable/pycall/ ) (not to be confused with PyCall) to Python (yes, this is no joke - this'll allow Basil to develop & maintain only a super tiny standard library)
5. seamless ["low-level" FFI for C/C++/Rust](https://slightknack.dev/passerine/ffi-hard/ ) libs (to cover the rest of the use cases) - note this FFI shall also support seamless interfacing with C/C++ structs/data_types
6. language support for "full" hierarchy of caches (from registers through L1... caches and RAM and SSD and HDD and network attached storage up to extremely long-term archiving storage like Amazon Glacier)

     E.g. I wrote once a "persistentdict" for Python whose aim was to be a "true" Python dict with the twist that everything added/removed/changed is being automatically persisted (with the highest guarantee the given OS supports) - the only difference to Python dict was initialization which needed two arguments (path to a file used as backing storage and a "namespace string" to support multiple persistent dicts with the same backing storage) - and if one used Python context managers with multiple such persistent dicts in the code block, then the changes made were transactional (fully ACID) unlike if used separately when only operations upon each separate persistentdict instance were guaranteed transactional (fully ACID).

    Working with that was a breeze (incl. easy optimizations if needed) compared to any other persistent API I've ever seen (I've even seen some benchmarks of big databases like PostgreSQL on server HW and was surprised that my persistentdict performed about the same in multithreaded write benchmarks on my old laptop with slow HDD :open_mouth: - I've checked it several times as I couldn't believe it, but yes, it was that bad with bigger DBs - probably due to their extremely complicated locking schemes etc.).

    For Basil I imagine something even more "first class" (pun intended with the [recent jam](https://github.com/langjam/jam0001 ) :wink:).

    Maybe just make all variables/arguments/return_values persistent by default (of course not naively otherwise we'd be feeling like we're running on 0.1MHz CPU, but maybe using some escape analysis, sampling of the "important state" or just smartly/semi-automatically determining save points, etc.)? If DBs can (more or less) do that, why not Basil?
4. Please add you own below in the comments!

(yeah, I totally admit some of these sound like [true scifi](https://github.com/elucent/scheme2d ), but hey, let's offer something unusual but extremely useful unlike other languages!)

**Comment by elucent** [comment]
Okay, gonna respond to each of these in turn:

1. Teishi seems...complicated? To the point I'm not entirely sure what it's doing in these examples...😓 But it's vaguely in the plans to support compile-time assertions to a deep level. Since Basil makes it relatively easy to manipulate compile-time evaluation (all code is evaluated at compile-time by default!) all we really need to enforce assertions is some kind of assertion/error primitive - which should be quite trivial to add as a compiler builtin. Since Basil functions are also generic (meaning dynamic at compile time) by default, we could add quite expressive assertions very naturally: 
```
def foo x? =
    if x < 0 then # reports compile error
        error "Expected non-negative argument in 'foo', found " + x as String
    # do function body...
```
Of course, in this case, `x < 0` will only be resolvable at compile time if the input `x` is resolvable at compile time. We could consider extending this with some kind of dependent typing...but that would be pretty involved. At bare minimum, asserting arbitrary conditions about compile-time constructs (like modules, types, etc) should be pretty straightforward.

2. Seems like it wouldn't be too hard to represent in Basil somehow! Not all syntax can be represented 1:1, there's still some context-free core syntax in Basil that is hard to work around (like parentheses or indentation for code lists). But you would at bare minimum be able to embed some kind of similarly-structured representation in the grammar, and theoretically it wouldn't be too hard to attach a code generator to the backend of that.

3. Async is a huge can of worms I'm not really qualified to make judgements about at the moment. My cursory answer to this is I'd rather have something more like green threads or goroutines or whatever, and support structured async through threads. But this is really up in the air at this point.

4. Seems like something like PythonCall is best left up to a third-party library - I assume it operates through some CPython API? Not sure Python is general enough to include in the language or stdlib core but I'd like to ensure Basil is powerful enough to express such an API effectively in userspace.

5. Basil already _sort of_ supports native compilation - I've successfully run small "hello world"-type programs (literally hello world, as well as factorial and recursive fibonacci) from a C main function, as well as called C functions from Basil using a past extern function interface. Since the backend is in the process of being totally rewritten at the moment, the exact interface we'll use going forward is kind of unclear. But ideally I'd like to support both static and dynamic linking with native object files, and support dynamic linking within Basil's JIT.

6. Oh man. This seems like a bit of a stretch...I'd say this would be best left to userspace, I don't think persistence is essential to enough use cases to merit making it the _default_ of the language. Interesting concept but Basil is getting big enough as-is...😅

**Comment by dumblob** [comment]
> 1. ...At bare minimum, asserting arbitrary conditions about compile-time constructs (like modules, types, etc) should be pretty straightforward.

I think this is the safe and good beginning. Later we could add some examination of the type itself to check for only certain aspects of the given type (see the rabbit hole [starting at 21:01](https://youtu.be/HfnjUCRzRKU?t=1261 ) to understand what I mean :wink:).

> 2. Seems like it wouldn't be too hard to represent in Basil somehow! Not all syntax can be represented 1:1, there's still some context-free core syntax in Basil that is hard to work around (like parentheses or indentation for code lists). But you would at bare minimum be able to embed some kind of similarly-structured representation in the grammar, and theoretically it wouldn't be too hard to attach a code generator to the backend of that.

Perfect. The goal wasn't to do 1:1 syntax, but something very closely resembling it and having the corresponding "expected" semantics.

> 3. Async is a huge can of worms I'm not really qualified to make judgements about at the moment. My cursory answer to this is I'd rather have something more like green threads or goroutines or whatever, and support structured async through threads. But this is really up in the air at this point.

What I wanted to say by that paragraph was actually that I want to strongly discourage you from implementing async support at the language level. There can be of course some backend support for it (e.g. for performance reasons), but it must not interfere with "true" parallelism, with error handling, etc. And second it must not influence the Basil language per se. Therefore I've proposed async as an independent part of stdlib (probably tier 2).

We can discuss this in a separate issue if you think this is too radical. But I think you're well aware that async is by far not a scalable solution to most problems (if you didn't yet, enjoy reading http://joeduffyblog.com/2015/11/19/asynchronous-everything/ and dozen of other posts about how async is a "cancer" etc. - I actually like it, but only if it's contained & well separated from the rest & explicit - as demonstrated e.g. by the Julia async support).

> 4. Seems like something like PythonCall is best left up to a third-party library - I assume it operates through some CPython API? Not sure Python is general enough to include in the language or stdlib core but I'd like to ensure Basil is powerful enough to express such an API effectively in userspace.

Yes, it uses CPython API. And yes, I meant it to be in userspace (tier 2 stdlib).

> 5. Basil already _sort of_ supports native compilation - I've successfully run small "hello world"-type programs (literally hello world, as well as factorial and recursive fibonacci) from a C main function, as well as called C functions from Basil using a past extern function interface. Since the backend is in the process of being totally rewritten at the moment, the exact interface we'll use going forward is kind of unclear. But ideally I'd like to support both static and dynamic linking with native object files, and support dynamic linking within Basil's JIT.

:+1:

> 6. Oh man. This seems like a bit of a stretch...I'd say this would be best left to userspace, I don't think persistence is essential to enough use cases to merit making it the _default_ of the language. Interesting concept but Basil is getting big enough as-is...sweat_smile

:stuck_out_tongue_winking_eye: Yep, it's crazy, but I think some tier 2 stdlib project might take that route - could be interesting to see it. I just don't necessarily want Basil to block such crazy but cool concepts by making a decision in its architecture or syntax which would essentially prevent such free use :wink:
